### ISSUE TITLE
Other deprecations

### ISSUE THREAD

**Issue by dpo** [ralna/ARCHDefs#12]
Is it really worth continuing to support the following platforms? Are they even still around?

- [ ] pc
- [ ] ppc
- [ ] sun
- [ ] aix
- [ ] cry
- [ ] alp
- [ ] i64

We could focus on pc64, mac64 and keep the "all" platform around for the occasional odd system?!

**Comment by nimgould** [comment]
I have looked at https://fortran-lang.org/en/compilers/ to see what is still around. I will remove alp and i64 as these seem to be dead. I'll also remove hpu and dux systems, and all of the old gcc/gfo* versions except the latest. This should significantly prune our support

**Comment by dpo** [comment]
Thanks. Are pc (32 bit), ppc, sun and CRAY still relevant?
