### ISSUE TITLE
There seems to be a typo in `select_arch`

### ISSUE THREAD

**Issue by zaikunzhang** [ralna/ARCHDefs#29]
Hello Nick (or anyone else),

Is the `"1")` in the following line a typo? It seems to be `"2")`. 

https://github.com/ralna/ARCHDefs/blob/af562acf078f6faed85647dca094187489505f5d/bin/select_arch#L85

Thank you!

Best regards,
Zaikun

**Comment by nimgould** [comment]
Yes, indeed, a recently introduced error. Corrected. Thank you, Zaikun!
